MyJavaMyAdmin/src/com/myjava/myadmin/beans/ChangeLocale.java
package com.myjava.myadmin.beans;

import java.io.Serializable;

import javax.enterprise.context.SessionScoped;
import javax.inject.Named;

@SessionScoped
@Named("ChangeLocale")
public class ChangeLocale implements Serializable {

	private static final long serialVersionUID = 1L;
	
	// la locale des pages
	private String locale="fr";

	//CONSTRUCT
	public ChangeLocale() {
		
	}
	
	//METHODS
	
	public void setFrenchLocale() {
		locale="fr";
		
	}
	public void setEnglishLocale() {
		locale="en";
		
	}
	
	
	//GET & SET
	public String getLocale() {
		return locale;
	}

	public void setLocale(String locale) {
		this.locale = locale;
	}
	
	

}

MyJavaMyAdmin/src/com/myjava/myadmin/beans/Server.java
package com.myjava.myadmin.beans;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

import javax.ejb.LocalBean;
import javax.enterprise.context.SessionScoped;

import org.primefaces.model.DefaultTreeNode;
import org.primefaces.model.TreeNode;

import com.mysql.cj.xdevapi.Schema;
import com.mysql.cj.xdevapi.Table;

@LocalBean
@SessionScoped
public class Server implements Serializable {

	private static final long serialVersionUID = 1L;

		private String adressServer ="mysqlx://localhost:33060";
		private TreeNode serverTree;
		//private TreeNode selectedNode;
	
		private HashMap<Schema, TreeNode> node = new HashMap<>();
		private List<Schema> listSchema;
		   
		public void initTreeview() {
		    	serverTree = new DefaultTreeNode("Serveur","DBserver", null);
		    	
		    	for (Schema schema : listSchema) {
		    		node.put(schema, new DefaultTreeNode("schema",schema.getName(), serverTree));	
					
		    		if (schema.getTables().size()!=0) {
		    			List<Table> tables =  new ArrayList<Table>();
		    			List<Table> views = new ArrayList<Table>();
		    			for(Table schemaGetTable : schema.getTables()) {
		    				if (schemaGetTable.isView()) {
								views.add(schemaGetTable);
							}else {
								tables.add(schemaGetTable);
							} 
						}
		    			if(!views.isEmpty()) {
		    				DefaultTreeNode nodeTables = new DefaultTreeNode("tables","Tables", node.get(schema));
		    				DefaultTreeNode nodeViews = new DefaultTreeNode("views","Views", node.get(schema));
		    				for (Table table : tables) {
			    				new DefaultTreeNode("table",table.getName(), nodeTables);
							}
		    				for (Table view : views) {
			    				new DefaultTreeNode("view",view.getName(), nodeViews);
							}
		    			}else {
		    				for (Table table : tables) {
			    				new DefaultTreeNode("table",table.getName(), node.get(schema));
							}
		    			}
		    				
					}		    		
		    	}	    	
		    }
		    

		public List<Schema> getListSchema() {
			return listSchema;
		}

		public void setListSchema(List<Schema> listSchema) {
			this.listSchema = listSchema;
		}

		public String getAdressServer() {
			return adressServer;
		}

		public void setAdressServer(String adressServer) {
			this.adressServer = adressServer;
		}

		public TreeNode getRoot() {
	        return serverTree;
	    }

		public void toInitSchemas(List<Schema> schemas) {
			this.listSchema=schemas;				
		}
//			public TreeNode getSelectedNode() {
//		        return selectedNode;
//		    }
//		 
//		    public void setSelectedNode(TreeNode selectedNode) {
//		        this.selectedNode = selectedNode;
//		    }
//		    
		   
}

MyJavaMyAdmin/src/com/myjava/myadmin/beans/User.java
package com.myjava.myadmin.beans;

import java.io.Serializable;

import javax.enterprise.context.SessionScoped;

@SessionScoped
public class User implements Serializable {

	private static final long serialVersionUID = 1L;
	
	private String userName;
	private String passWord;
	
	
	public String getUserName() {
		return userName;
	}
	public void setUserName(String userName) {
		this.userName = userName;
	}
	public String getPassWord() {
		return passWord;
	}
	public void setPassWord(String passWord) {
		this.passWord = passWord;
	}
}

MyJavaMyAdmin/src/com/myjava/myadmin/controller/Controller.java
package com.myjava.myadmin.controller;

import java.io.Serializable;
import java.sql.SQLException;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;

import org.slf4j.LoggerFactory;

import com.myjava.myadmin.beans.User;
import com.myjava.myadmin.beans.Server;

import com.mysql.cj.xdevapi.Client;
import com.mysql.cj.xdevapi.ClientFactory;
import com.mysql.cj.xdevapi.RowResult;
import com.mysql.cj.xdevapi.Schema;
import com.mysql.cj.xdevapi.Session;
import com.mysql.cj.xdevapi.Table;
import com.mysql.cj.xdevapi.Row;
import com.mysql.cj.xdevapi.SelectStatement;

@SessionScoped
@Named("Controller")
public class Controller implements Serializable {
	private static final long serialVersionUID = 1L;
	private static final org.slf4j.Logger LOGGER_SL4J = LoggerFactory.getLogger(Controller.class.getName());
	
	@Inject
	private User user;
	@Inject
	private Server server;	
		
	private Client client;
	private Session session;
	private Schema currentSchema;
	private Table currentTable;
	private RowResult resultat;
	private List<Row> rows;
		
	@PostConstruct
	public void init() {
		LOGGER_SL4J.info("Controller init");		
	}
	
	public Controller() {		
		LOGGER_SL4J.info("Controller construct OK");
		
	}
	
	public void createClient() {
		ClientFactory clientFactory = new ClientFactory();
		this.client= clientFactory.getClient(this.server.getAdressServer()+"?user="+this.user.getUserName()+"&password="+this.user.getPassWord()+"",
				"{\"pooling\":{\"enabled\":true, \"maxSize\":8, \"maxIdleTime\":30000, \"queueTimeout\":10000} }");
	}
	
	public String index() {		
		LOGGER_SL4J.info("Controller index OK");
		return "index";
	}
	
	public String oneSchema(String schemaName) {
		this.currentSchema=this.session.getSchema(schemaName);
		return "oneschema?faces-redirect=true";		
	}	

	public String infoTable(String table) {
		this.currentTable=this.currentSchema.getTable(table);
		SelectStatement stmt = this.currentTable.select();
		this.resultat = stmt.execute();		
		this.rows=this.resultat.fetchAll();		
		return "infotable?faces-redirect=true";	
	}
	
	
	public String toLogIn() throws SQLException {
		FacesMessage message =new FacesMessage("Login OK");
		FacesContext.getCurrentInstance().addMessage(null, message);
		System.out.println("login Ok, username " + this.user.getUserName());
		this.createClient();
		this.session=this.client.getSession();		
		this.server.toInitSchemas(this.session.getSchemas());
		this.server.initTreeview();
		return "index?faces-redirect=true";
	}
	
	public Schema getCurrentSchema() {
		return currentSchema;
	}
	public void setCurrentSchema(Schema currentSchema) {
		this.currentSchema = currentSchema;
	}
	public Table getCurrentTable() {
		return currentTable;
	}
	public void setCurrentTable(Table currentTable) {
		this.currentTable = currentTable;		
	}
	public RowResult getResultat() {
		return resultat;
	}
	public void setResultat(RowResult resultat) {
		this.resultat = resultat;
	}
	public User getUser() {
		return user;
	}
	public Server getServer() {
		return server;
	}

	public List<Row> getRows() {
		return rows;
	}

	public void setRows(List<Row> rows) {
		this.rows = rows;
	}
	
	
}

MyJavaMyAdmin/WebContent/index.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:f="http://xmlns.jcp.org/jsf/core">

<ui:composition template="/template/mylayout.xhtml">

	<ui:define name="content">
			<h:form styleClass="main__form">
				<p:dataTable id="infoDatabase" var="schema" value="#{Controller.server.listSchema}"
				tableStyleClass="infoTable" rowStyleClass="infoTableLigne" rowIndexVar="id">
					<f:facet name="header">List of database</f:facet>
					<p:column headerText="#" style="width:10%">
						<h:outputText value="#{id}"/>
					</p:column>
					<p:column headerText="Database">
						<p:commandLink  action="#{Controller.oneSchema(schema.name)}" ajax="false">
								<h:outputText value="#{schema.name}"/>
							</p:commandLink>
					</p:column>
					<p:column headerText="nd de Tables" style="width:30%">
						<h:outputText value="#{schema.tables.size()}"/>
					</p:column>
				</p:dataTable>				
			</h:form>	
	</ui:define>
		
</ui:composition>

</html>

MyJavaMyAdmin/WebContent/infotable.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:f="http://xmlns.jcp.org/jsf/core">

<ui:composition template="/template/mylayout.xhtml">

	<ui:define name="content">
		<p:panel id="panel" header="Infos">
			<p:panelGrid columns="2">
				<h:outputLabel for="schemaName" value="Nom Schema : "/>
				<h:outputText id="schemaName" value="#{Controller.resultat.columns[0].schemaName}"/>
				
				<h:outputLabel for="tableName" value="Nom Table : "/>
				<h:outputText id="tableName" value="#{Controller.resultat.columns[0].tableName}"/>
				
				<h:outputLabel for="tableLabel" value="Label Table : "/>
				<h:outputText id="tableLabel" value="#{Controller.resultat.columns[0].tableLabel}"/>
			</p:panelGrid>
			
		</p:panel>
		<h:form id="form">
		<p:growl id="msgs" showDetail="true"/>
		<p:tabView dynamic="true" cache="true" effect="fold" styleClass="tabView">
			<p:tab title="Structure" titleStyleClass="tabView_tittle">
				
					
					<p:dataTable id="infoTable" var="column" value="#{Controller.resultat.columns}" editable="true" 
						tableStyleClass="infoTable" rowStyleClass="infoTableLigne" rowIndexVar="id">
						<f:facet name="header">Infos table</f:facet>
						
						<p:ajax event="rowEdit" listener="#{dtEditView.onRowEdit}" update=":form:msgs" />
						<p:ajax event="rowEditCancel" listener="#{dtEditView.onRowCancel}" update=":form:msgs" />
						
						<p:column headerText="#" style="width:24px">
						<h:outputText value="#{id}"/>
						</p:column>
			
						<p:column headerText="#{lbl['column.columnName']}">
							<p:cellEditor>
								<f:facet name="output"><h:outputText value="#{column.columnName}"/></f:facet>
								<f:facet name="input"><h:inputText value="#{column.columnName}"/></f:facet>
							</p:cellEditor>				
						</p:column>
									
						<p:column headerText="#{lbl['column.dataType']}">
							<h:outputText value="#{column.type}"/>
						</p:column>		
							
						
						<p:column headerText="Interclassement">
							<h:outputText value="#{column.collationName}"/>
						</p:column>
						
						<p:column headerText="Null">
							<h:outputText rendered="#{column.nullable eq true}" value="oui"/>				
						</p:column>
						<p:column headerText="isAutoIncrement">
							<h:outputText rendered="#{column.autoIncrement eq true}" value="x"/>				
						</p:column>
			
						<p:column style="width:35px" headerText="Action">
            				<p:rowEditor />
        				</p:column>
					</p:dataTable>	
				
				
			</p:tab>
			<p:tab title="Parcourir" titleStyleClass="tabView_tittle">
				<p:dataTable id="tableRow" value="#{Controller.rows}" var="row"	rowIndexVar="rowIndex" tableStyleClass="infoTable" 
					rowStyleClass="infoTableLigne" resizableColumns="true"  liveResize="true"
					draggableColumns="true">
					
					
	<f:facet name="header">
        List of data
 
		<p:commandButton id="toggler" type="button" value="Columns" style="float:right" icon="pi pi-align-justify" />
        <p:columnToggler datasource="tableRow" trigger="toggler" />
    </f:facet>
					
					<p:columns headerText="#{columnName}" value="#{Controller.resultat.columnNames}" 
					 var="columnName" columnIndexVar="index" toggleable="true">
					
						<h:outputText value="#{row.getString(index)}"/>
						
					</p:columns>
				
				</p:dataTable>
			</p:tab>
		</p:tabView>
		</h:form>	
		</ui:define>
		
</ui:composition>
</html>

MyJavaMyAdmin/WebContent/loginServer.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:f="http://xmlns.jcp.org/jsf/core">

<ui:composition template="/template/mylayoutlogin.xhtml">
	
	<ui:define name="content">
		
		<h:form id="connexionForm">
			<p:fieldset legend="Server Connection">			
				<p:panelGrid columns="2">						
					<h:outputLabel value="Address Server"/>
					<h:inputText id="server" value="#{Controller.server.adressServer}"/>
					<h:outputLabel value="#{lbl['server.username']}"/>
					<h:inputText id="username" value="#{Controller.user.userName}"/>
					<h:outputLabel value="#{lbl['server.password']}"/>				
					<h:inputSecret id="password" value="#{Controller.user.passWord}"/>
				</p:panelGrid>				
				<h:commandButton icon="pi pi-sign-in" id="signbtn" value="#{lbl['server.connexion_btn']}" action="#{Controller.toLogIn}"/>
			</p:fieldset>			
		</h:form>
	
		</ui:define>
		
</ui:composition>

</html>

MyJavaMyAdmin/WebContent/oneschema.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:f="http://xmlns.jcp.org/jsf/core">

<ui:composition template="/template/mylayout.xhtml">

	<ui:define name="content">
		<p:panel id="panel" header="Infos">
			<p:panelGrid columns="2">
				<h:outputLabel for="schemaName" value="Nom Schema : "/>
				<h:outputText id="schemaName" value="#{Controller.currentSchema.name}"/>				
			</p:panelGrid>
		</p:panel>
		<p:panel header="Contenu">
			<h:form id="form">
				<p:dataTable var="table" value="#{Controller.currentSchema.tables}" 
				rowIndexVar="id" tableStyleClass="infoTable" rowStyleClass="infoTableLigne">
					
					<p:column headerText="#" style="width:5%">
						<h:outputText value="#{id}"/>
					</p:column>
					<p:column>
						<p:commandLink action="#{Controller.infoTable(table.name)}" ajax="false">
							<h:outputText value="#{table.name}"/>
						</p:commandLink>
					</p:column>
					<p:column headerText="Lignes" style="width:10%">
						<h:outputText value="#{table.count()}"/>
					</p:column>
					<p:column headerText="Type" style="width:10%" >
						<h:outputText value="#{table.isView()==true?'view' : 'InnoDB'}"/>
					</p:column>
				</p:dataTable>
			</h:form>
		</p:panel>
	</ui:define>
		
</ui:composition>
</html>

MyJavaMyAdmin/WebContent/template/header.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:f="http://xmlns.jcp.org/jsf/core">

<ui:composition>
	 	
	 	<h1 class="header__title"><h:outputText value="#{lbl['header.title']}"/></h1>
		<h2 class="header__subtitle"><h:outputText value="#{lbl['header.title2']}"/></h2>
	 		
</ui:composition>

</html>

MyJavaMyAdmin/WebContent/template/menu.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:f="http://xmlns.jcp.org/jsf/core">

<ui:composition>
	
	<h:form id="languageForm" class="header__form__language">
		<p:fieldset legend="#{lbl['welcome.chooseLanguage']}" class="fieldset__language" >
	 	 	<p:panelGrid columns="2">
				<h:commandLink action="#{ChangeLocale.setFrenchLocale}" id="language__link__french" class="flag-icon flag-icon-fr" />
				<h:commandLink action="#{ChangeLocale.setEnglishLocale}" id="language__link__english" class="flag-icon flag-icon-gb"/>
			</p:panelGrid>	
	 	</p:fieldset>			
	</h:form>
	
</ui:composition>
</html>

MyJavaMyAdmin/WebContent/template/mylayout.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
          "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:f="http://xmlns.jcp.org/jsf/core">
<f:view locale="#{ChangeLocale.locale}">
	<h:head>
		<title><h:outputText value="#{lbl['welcome.title']}"/></title>		
	</h:head>
	
	<body>
 	<h:outputStylesheet library="css" name="reset.css" /> 
 	<h:outputStylesheet library="css" name="theme.css" /> 
 	<h:outputStylesheet library="css" name="flag-icon.css" />
 	<h:outputStylesheet library="primefaces" name="primeicons/primeicons.css"/>
	
<!-- 	<ui:debug hotkey="x" rendered="#{initParam['javax.faces.FACELETS_DEVELOPMENT']}"/> -->
	
			<div id="header" class="header">
				<ui:include src="/template/header.xhtml" />
			</div>
			<div id="menu" class="menu">	
				<ui:include src="/template/menu.xhtml" />
			</div>
			
			<div id="treeview" class="treeview">
				<ui:include src="/template/treeview.xhtml"/>				
			</div>
			
			
			<div id="content" class="main">
			
				<ui:insert name="content"/>				
			</div>
	
			<div id="footer" class="footer">
				<ui:insert name="footer"/>			
			</div>
		
	
	</body>
</f:view>
</html>

MyJavaMyAdmin/WebContent/template/mylayoutlogin.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
          "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:f="http://xmlns.jcp.org/jsf/core">
<f:view locale="#{ChangeLocale.locale}">
	<h:head>
		<title><h:outputText value="#{lbl['welcome.title']}"/></title>		
	</h:head>
	
	<body>
 	<h:outputStylesheet library="css" name="reset.css" /> 
 	<h:outputStylesheet library="css" name="theme.css" /> 
 	<h:outputStylesheet library="css" name="flag-icon.css" />
	
<!-- 	<ui:debug hotkey="x" rendered="#{initParam['javax.faces.FACELETS_DEVELOPMENT']}"/> -->
	
			<div id="header" class="header">
				<ui:include src="/template/header.xhtml" />
			</div>
			<div id="menu" class="menu">	
				<ui:include src="/template/menu.xhtml" />
			</div>
			
			<div id="treeview" class="treeview">							
			</div>
			
			
			<div id="content" class="main">			
				<ui:insert name="content"/>				
			</div>
	
			<div id="footer" class="footer">
				<ui:insert name="footer"/>			
			</div>
		
	
	</body>
</f:view>
</html>

MyJavaMyAdmin/WebContent/template/treeview.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:f="http://xmlns.jcp.org/jsf/core">

<ui:composition>
	<h:form id="formTree" styleClass="treeview" >
		 <p:growl id="messages" showDetail="true" />
			<p:panel header="Map of server">
				<p:tree value="#{Controller.server.root}" var="node" styleClass="treecontainer">

		     		<p:treeNode styleClass="treenode" type="schema" icon="pi pi-clone">
		     			<p:commandLink action="#{Controller.oneSchema(node)}" ajax="false">
		     				<h:outputText value="#{node}" />		           		
		     			</p:commandLink>			           		
		        	</p:treeNode>
		        	<p:treeNode styleClass="treenode" type="table" icon="pi pi-table">
			        	<p:commandLink action="#{Controller.infoTable(node)}" ajax="false">
			     				<h:outputText value="#{node}" />		           		
			     		</p:commandLink>		
		        	</p:treeNode>
		        	<p:treeNode styleClass="treenode" type="view" icon="pi pi-th-large">
		     			<p:commandLink action="#{Controller.infoTable(node)}" ajax="false">
		     				<h:outputText value="#{node}" />		           		
		     			</p:commandLink>			           		
		        	</p:treeNode>
			        	<p:treeNode styleClass="treenode" type="tables" icon="pi pi-table">
			     				<h:outputText value="#{node}" />		           		
			        	</p:treeNode>
		        	<p:treeNode styleClass="treenode" type="views" icon="pi pi-th-large">
		     				<h:outputText value="#{node}" />		           		
		        	</p:treeNode>
	   			 </p:tree>
			</p:panel>
		
		</h:form>	
</ui:composition>
</html>